### ISSUE TITLE
Connect to PC no data on /joy topic on pc

### ISSUE THREAD

**Issue by droter** [UbiquityRobotics/ubiquity_main#125]
Hi,

Image: 2018-06-07-ubiquity-xenial-lxde

I have added my pc and raspberry pi IP address to the hosts file on both my PC and RPi.  I have added the ROS_MASTER and ROS_HOSTNAME_URI to both.  

/etc/hosts file on image:
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1       ubiquityrobot ubiquityrobot.local
192.168.43.129  tractor
192.168.43.48   mypc

If I ssh into the RPi and publish a topic from the command line I can see the data on my PC.  
RPi $ rostopic pub -r 10 /turtle1/cmd_vel geometry_msgs/Twist  '{linear:  {x: 0.1, y: 0.0, z: 0.0}, angular: {x: 0.0,y: 0.0,z: 0.0}}'

mypc $ rostopic echo /turtle1/cmd_vel
linear: 
  x: 0.1
  y: 0.0
  z: 0.0
angular: 
  x: 0.0
  y: 0.0
  z: 0.0

$ rostopic info /turtle1/cmd_vel
Type: geometry_msgs/Twist
Publishers: 
 * /rostopic_1666_1532041664121 (http://tractor:38879/)

If I try to echo the /joy topic from my pc no data shows up.

It looks like the node is being published on http://ubiquityrobot.local.  Could this be the issue?
$ rostopic info /joy
Type: sensor_msgs/Joy
Publishers: 
 * /joy_node (http://ubiquityrobot.local:40945/)

Thanks,

Matt

**Comment by rohbotics** [comment]
Do you have a joystick connected? Which one?

There will be no joy messages being published if you don't have a Logitech Joystick plugged in.

**Comment by droter** [comment]
Yes, I have the joystick plugged into the Raspberry Pi.

When I echo the topic from the Pi:
ubuntu@ubiquityrobot:~$ rostopic echo /cmd_vel
linear: 
  x: 0.75
  y: 0.0
  z: 0.0
angular: 
  x: 0.0
  y: 0.0
  z: 0.0

When I echo the topic from my pc:
$ rostopic echo /cmd_vel
(No Data)

I can see the /joy topic and /cmd_vel from the Raspberry Pi.  I can see the topics on my laptop but no data.  From answers.ros.org they suggest it is a network issue.

The only difference I can see:
One node is being published by /joy_node (http://ubiquityrobot.local:40945/)
And the other is being published by /rostopic_1666_1532041664121 (http://tractor:38879/)

I can see topic data from http://tractor but not http://ubuquityrobot.local.

**Comment by rohbotics** [comment]
Sounds like there is a networking problem.

What is the output of `env | grep ROS` ?

**Comment by droter** [comment]
On mypc:
$ env | grep ROS
ROS_ROOT=/opt/ros/kinetic/share/ros
ROS_PACKAGE_PATH=/home/matt/lino_ws/src:/home/matt/ros-a_ws/src:/opt/ros/kinetic/share
ROS_MASTER_URI=http://tractor:11311
ROS_VERSION=1
ROS_HOSTNAME=mypc
ROS_DISTRO=kinetic
ROS_ETC_DIR=/opt/ros/kinetic/etc/ros

on the Pi:
ubuntu@ubiquityrobot:~$ env | grep ROS
ROS_ROOT=/opt/ros/kinetic/share/ros
ROS_PACKAGE_PATH=/home/ubuntu/catkin_ws/src:/opt/ros/kinetic/share
ROS_MASTER_URI=http://tractor:11311
ROS_VERSION=1
ROS_PARALLEL_JOBS=-j2
ROS_HOSTNAME=tractor
ROSLISP_PACKAGE_DIRECTORIES=/home/ubuntu/catkin_ws/devel/share/common-lisp
ROS_DISTRO=kinetic
ROS_ETC_DIR=/opt/ros/kinetic/etc/ros

**Comment by rohbotics** [comment]
We highly recommend using the Raspberry Pi as the master, there are many advantages to this.

Also the ROS_HOSTNAME needs to be the hostname of the computer that it is set on, and be accessible from the other computers on the network.

What is the hostname of your pc? What is tractor?

**Comment by droter** [comment]
roscore is running on the Pi (tractor) and I am trying to read the /joy node from my laptop (mypc). 

/etc/hosts file on image:
127.0.0.1 localhost
::1 localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

127.0.1.1 ubiquityrobot ubiquityrobot.local
192.168.43.129 tractor
192.168.43.48 mypc

**Comment by droter** [comment]
This node is running on http://ubiquityrobot.local:36777?  Why doesn't it say the ROS_MASTER_URI


ubuntu@ubiquityrobot:~$ rosnode info /teleop_twist_joy
--------------------------------------------------------------------------------
Node [/teleop_twist_joy]
Publications: 
 * /cmd_vel [geometry_msgs/Twist]
 * /rosout [rosgraph_msgs/Log]

Subscriptions: 
 * /joy [sensor_msgs/Joy]

Services: 
 * /teleop_twist_joy/get_loggers
 * /teleop_twist_joy/set_logger_level


contacting node http://ubiquityrobot.local:36777/ ...
Pid: 1120
Connections:
 * topic: /rosout
    * to: /rosout
    * direction: outbound
    * transport: TCPROS
 * topic: /joy
    * to: /joy_node (http://ubiquityrobot.local:40671/)
    * direction: inbound
    * transport: TCPROS

**Comment by rohbotics** [comment]
Ahh ok, I see the problem.

Environment variables are shell-local on linux, not global. So when you are setting the ROS_MASTER_URI environment variable you are not changing for the service that runs it on boot.

Please edit /etc/ubiquity/env.sh, which is where the bootup launch process gets its environment configuration. This is also sourced into your shell by default on the Raspberry Pi.

Rohan

**Comment by droter** [comment]
Yes! It works.

Very cool.  Thanks for your help.

Matt

**Comment by rohbotics** [comment]
No problem. 

Good luck with your project!

In the future, questions like this are better suited for https://forum.ubiquityrobotics.com/, where they might get more visibility.
