### ISSUE TITLE
Issues with follow me (see description)

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/ubiquity_main#144]
while trying the followme example. As instructed, i executed

sudo systemctl stop magni-base

roslaunch magni_demos fiducial_follow.launch

 

When magni detects the fiducial (49), there is an error message:

LookupException: "base_link" passed to lookupTransform argument target_frame does not exist. / Could not get tf for fid49

and indeed a quick "rosrun tf view_frames" reveils that no tf data is received.

I had to stop the script.

sudo systemctl start magni-base

reexecute the script

then magni follows me.

 

==> is it a bug in the documentation

**Comment by rohbotics** [comment]
Fixed. 

https://forum.ubiquityrobotics.com/t/fiducial-follow-error/117/4
