### ISSUE TITLE
Issues with remote connect

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/ubiquity_main#145]
while trying the followme example. As instructed, i executed

sudo systemctl stop magni-base

roslaunch magni_demos fiducial_follow.launch

 

When magni detects the fiducial (49), there is an error message:

LookupException: "base_link" passed to lookupTransform argument target_frame does not exist. / Could not get tf for fid49

and indeed a quick "rosrun tf view_frames" reveils that no tf data is received.

I had to stop the script.

sudo systemctl start magni-base

reexecute the script

then magni follows me.

 

==> is it a bug in the documentation

**Comment by jrlandau** [comment]
I don't understand why you closed this.  Sounds like there is at least some
warning missing from the docs.

**Comment by davecrawley** [comment]
We have another related issue for which the fix is the same. We just thought it best to close out the duplicate purely for administrative reasons. We still have to work on this issue.
