### ISSUE TITLE
When you hit k button on teleop it doesn't stop instantly (acceleration limits)

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/ubiquity_main#148]

**Comment by rohbotics** [comment]
This looks to be a case of too low acceleration limits, increasing them makes the robot stop quickly.

**Comment by rohbotics** [comment]
See https://github.com/UbiquityRobotics/magni_robot/commit/ad2deb933d3df8299c913e29368c23e109c9cdaf
