### ISSUE TITLE
Prevent off-by-one on Rpi

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/ubiquity_main#153]

**Comment by rohbotics** [comment]
This is for preventing a 'sideways' offset while trying to plug the raspberry pi in.

**Comment by mjstn** [comment]
Version 5.2 MCB is attempting to fix this.  We will evaluate if what was done was good enough as we evaluate version 5.2 MCB in late 2019

**Comment by rohbotics** [comment]
@mjstn Would you call this done?

**Comment by mjstn** [comment]
We have resolved it in a mediocre way but I have put numerous strong warnings in Learn pages as well.  So I feel this can be resolved 'best effort'.  The key thing is tall standoffs installed on MCB on both sides of tall RPi connector and those are on the BOM now.

**Comment by rohbotics** [comment]
Ok, I will call this done then. Just trying to make sure that we don't have a bunch of junk floating around our backlog.
