### ISSUE TITLE
Documentation for Robot Commander

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/ubiquity_main#16]

**Comment by anfederman** [comment]
two draft documents pushed to ubiquity_main,   UR_RC(robot commander), logitech_qs.
Documents needed:  Starting in default AP mode,  Connecting your robot to WiFi.  I can't write either one, because we haven't decided how we are doing this.

**Comment by anfederman** [comment]
please review drafts, edit push back to ubiquity_main
