### ISSUE TITLE
3.3 Volt Regulator

### ISSUE THREAD

**Issue by rohbotics** [UbiquityRobotics/ubiquity_main#172]
ADD ONE

**Comment by mjstn** [comment]
This moves to In Progress now.   We have included an onboard 3.3V regulator driven from onboard 5V main supply.  There are jumpers so we could use RaspberryPi 3.3V but we will load parts so we use onboard 3.3V.

**Comment by mjstn** [comment]
MCB board version 5.2 has an onboard 3.3V regulator which will roll into production in late 2019 or perhaps early 2020 if schedules hold.

**Comment by mjstn** [comment]
The rev 5.2 board has this now and it works so this issue is closed.

**Comment by mjstn** [comment]
The rev 5.2 board has this now and it works so this issue is closed.
