### ISSUE TITLE
GPIO Freeze Raspberry pi

### ISSUE THREAD

**Issue by unl0ck** [UbiquityRobotics/ubiquity_main#174]
If I want to use RPi.GPIO my RPI Freeze, I read it is, because using Kernel 4.9 I tried to roll back to 4.4 but it destroyed my kernel and the downgrade was not successful.
I used your newest Image

**Comment by rohbotics** [comment]
Take a look at this thread https://forum.ubiquityrobotics.com/t/ubuntu-mate-and-rpi-gpio-kernel-settngs/234

**Comment by unl0ck** [comment]
awesome Thank You very much for Help
