### ISSUE TITLE
Clock failure issue

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/ubiquity_main#187]
Upon boot 2 examples of Magni running 2019-02-10 image each with a different MCB version (one was 4.9 the other was 5.0) encountered difficult with clock sync. We checked the battery, battery voltage and whether the battery was seated correctly and that all seemed to **not** be the problem. When the robot re-boot they return a date of 2001 even when the date had been set.

**Comment by rohbotics** [comment]
Thanks for the detailed issue, i will look into it

**Comment by rohbotics** [comment]
We haven't seen this issue since, so maybe we just got bad chips somehow?
