### ISSUE TITLE
Uncontrolled motor movement after killing motor node

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/ubiquity_main#189]
Start magni motor node
Publish a twist message periodically on /cmd_vel (e.g., 0.1m/s forward, 30Hz)
Observe Magni moves forward as expected
Stop motor node
Observe Magni stops as expected
Stop publishing messages on /cmd_vel
Start magni motor_node
Observe Magni is moving at max velocity for a short period of time seemingly proportional to the original velocity.
This looks like the firmware’s integral is winding up when it is in an unconnected state.
Since we regard this kind of uncontrolled movement as a security issue, we would greatly appreciate help with it.

**Comment by mjstn** [comment]
This has been fixed in hardware from MCB 5.x versions combined with firmware fixes for ESTOP and PID related code.   This was first addressed in firmware version v32 and was later emproved upon in v35 firmware.    I believe this to be resolved.

**Comment by rohbotics** [comment]
Closing this due to age, and what we think is a solution with a lack of reproduction since.
