### ISSUE TITLE
Improve Switchboard

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/ubiquity_main#191]
-Robust switches
-Robust charging port
-Half watt resistors
-Couple of holes for external E-Stop switch

**Comment by rohbotics** [comment]
@mjstn I think this belongs in review/test now, correct?

**Comment by mjstn** [comment]
Yes, this is well into review/test and very close to 'done' pending a couple customers feedback.
We have boards in a state we feel is fully covering 'robust charging port', 'half watt resistors' and jacks for external E-Stop as well as main power switches.    
We have all but kicked off the 'robust switches' part of this at this time.  Maybe some later work, new issue.
