### ISSUE TITLE
Documentation for Magni in Gazebo

### ISSUE THREAD

**Issue by rohbotics** [UbiquityRobotics/ubiquity_main#195]

**Comment by rohbotics** [comment]
This is what we have https://learn.ubiquityrobotics.com/simulation

**Comment by jrlandau** [comment]
This should be assigned for review to someone other than me, as I am the
person what wrote it.

**Comment by rohbotics** [comment]
Agreed. @davecrawley can you assign this to someone in the test group?

**Comment by rohbotics** [comment]
Considering the number of people that we know to have gotten the simulation working, I am closing this.
