### ISSUE TITLE
Rohan special antenna

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/ubiquity_main#20]

**Comment by rohbotics** [comment]
https://www.amazon.com/Super-Power-Supply-Soldering-WZR-HP-G450H/dp/B00DMHSODS/ref=sr_1_6?ie=UTF8&qid=1494174792&sr=8-6&keywords=ufl+2.4ghz+antenna

**Comment by rohbotics** [comment]
Ordered

**Comment by davecrawley** [comment]
The antenna have arrived
