### ISSUE TITLE
Pi 4

### ISSUE THREAD

**Issue by SohaibS2E** [UbiquityRobotics/ubiquity_main#200]
Hello,
I am using the new pi 4 and the current ubiquity image release is not working.
When would you release an image for Pi4?
Thank you in advance.

This can be considered done when
1) The new image has been developed and is being built on our build system.
2) The image that is built on our build system has been tested by running that image on a Pi 4 through the steps contained in the documentation on learn.ubiquityrobotics.com
3) The critical elements of Driving, AP mode and Wifi have also been tested on the RPi 3B+
4) The warehouse in Hong Kong has destroyed all SD cards with the old distro that hasn't been placed in a robot.

**Comment by Mango-kid** [comment]
I posted an image for ROS here. It should work for most ROS things, still working on some package builds. 
[Pi4 ROS CV Image](https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=245106)

**Comment by SohaibS2E** [comment]
Does it have opencv on python2 and 3?

**Comment by SohaibS2E** [comment]
@Mango-kid Thank you!, great image.
