### ISSUE TITLE
Server Certificate Verification Failed

### ISSUE THREAD

**Issue by nikunjkragr** [UbiquityRobotics/ubiquity_main#204]
![WhatsApp Image 2019-07-10 at 11 57 32 (2)](https://user-images.githubusercontent.com/42914312/60945851-5904d480-a30a-11e9-9b29-8ce16f7d3d24.jpeg)
Failed to fetch https://packages.ubiquityrobotics.com/ubuntu/ubiquity/dists/xenial/main/binary-armhf/Packages server certificate verification failedFailed to fetch https://packages.ubiquityrobotics.com/ubuntu/ubiquity/dists/xenial/main/binary-armhf/Packages server certificate verification failed
ERROR showing while running command sudo apt-get update

**Comment by rohbotics** [comment]
Sounds like your ca-certificates are outdated. Go ahead and run `sudo apt-get update` and `sudo apt-get upgrade` which should update your certificates, then you can run those commands again without issue.

**Comment by nikunjkragr** [comment]
I am getting this error while I am running the above command i.e. Sudo apt-get update

**Comment by rohbotics** [comment]
Please ignore the error, and run `sudo apt upgrade` this should make the command work again without error.
