### ISSUE TITLE
robot.yaml needs commented out line for upward camera

### ISSUE THREAD

**Issue by mjstn** [UbiquityRobotics/ubiquity_main#207]
To help on syntax for camera orientation we need a line commented out in /etc/ubiquity/robot.yaml   

So the first 2 lines would then look like this

# Robot Configuration
raspicam: {'position' : 'downward'}

**Comment by rohbotics** [comment]
Thanks, we really should have had that already.

I added to to the build scripts, the next image should have that built in.
