### ISSUE TITLE
Unable to login to my Raspberry 

### ISSUE THREAD

**Issue by samurairepo** [UbiquityRobotics/ubiquity_main#209]
Hello,
please I tried to follow the instructions on https://downloads.ubiquityrobotics.com/pi.html
I was able to run it and I am the login prompt.
I can enter as Guest, but I have limited rights (sudo adduser XXX - asks for guest password)
What is the sudo password ? How do I create new user ?
EDIT: You can delete this, I am retarded sorry

**Comment by rohbotics** [comment]
Instead of logging in as Guest, log in as 'Ubuntu user' and use the password `ubuntu`

**Comment by rohbotics** [comment]
@samurairepo Just noticed your edit, don't worry about it, we all have those days.

Good luck with whatever you are using our image for! Please consider "buying us a coffee" via the donate button on the downloads page or Paypal to tips@ubiquityrobotics.com.

**Comment by rohbotics** [comment]
Closing this because it is resolved.
