### ISSUE TITLE
PiFi should indicate with a different blink rates for better user feedback

### ISSUE THREAD

**Issue by mjstn** [UbiquityRobotics/ubiquity_main#212]
When access point is active we see a 2 blink per second rate on LED1 on the Sonar board.
In this mode if PiFi has no defined networks to connect to we are Access Point mode only.

Now if we define a wifi network to connect to we will connect after reboot.
In this state we are connected to users wifi network BUT the led still blinks at 2 times per second.
**We should blink at perhaps 1 time a second so user knows if it is Access Point or his WiFi that is connected.**   This had caused quite a bit of confusion in the filed for users to know what case is active.

A second issue is if user wants his network or nothing at all we need some mode for PiFi to tell PiFi to never go to access point mode.  This has it's own evils but is being requested often by users.

A PiFi option should exist so in the case there IS a user defined network (even if we cannot connect) the PiFi will NOT go into access point.    If there is NO user defined wifi network PiFi should always go to Access Point logic as it does today.

There are a very small number of users that want to NEVER have AP but they generally are security focused and want the chip itself to be removed so those users we should not try to address in software solutions and only in hardware solutions so it is just not possible ever.

In any case where there is no connection at all it would be nice for PiFi to at least show it is running and in this case perhaps one short blink every 5 seconds could indicate no AP or user wifi is connected BUT there is a defined user wifi, we just cannot see it.

A final case is there is no defined user wifi and in this case we should always go to access point even if user has tried to set no Access Point.  The No access point option should mean  'Do not go to access point if user has defined ANY possible user wifi network.

**Comment by mjstn** [comment]
As a side note I will add that the WiFi led which is normally only on the Sonar Board is going to be also on MCB version 5.2 and later and labeled as  'WiFi'

**Comment by mjstn** [comment]
Update:  The WiFi led is working now on the new rev 5.2 MCB.  This is great debug and all users will start to have this without the Sonar board.  The Sonar board continues to have it's own WiFi led

**Comment by rohbotics** [comment]
How does the following sound:
- Initializing 500ms on, 500ms off
- AP mode: 100ms on 500ms off (current blink rate)
- Connected to a network: 100ms on 2000ms off

**Comment by rohbotics** [comment]
As per our discussion about the 2 opposite LEDs I went with the following.

Initializing 100ms on, 300ms off
AP mode: 100ms on 1000ms off
Connected to a network: 100ms on 2000ms off

**Comment by rohbotics** [comment]
https://github.com/rohbotics/pifi/pull/19

**Comment by rohbotics** [comment]
@davecrawley We need a test plan for this, I can write it up but who should do the testing?
