### ISSUE TITLE
RPi 4 boot issue

### ISSUE THREAD

**Issue by rpilab3k** [UbiquityRobotics/ubiquity_main#213]
I cannot get the mot current image to boot on a RPi 4. It boots on a RPi 3 B+. Is there a work around or an ETA on when RPi 4 will be supported?

**Comment by rohbotics** [comment]
You should track this thread for information on Pi4 support. https://forum.ubiquityrobotics.com/t/ros-image-on-raspberry-pi-4/326/28

In short, we can make it boot, but Wifi (specifically AP mode) is not really working yet.

**Comment by rohbotics** [comment]
Closing this because it is a duplicate of #200
