### ISSUE TITLE
Floor following conveyobot - breadcrumb" robot

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/ubiquity_main#215]
This can be considered done when.

1) We have a distribution which can meet the requirements of the documentation described here:

https://docs.google.com/document/d/1t24kzd8stWFtDZgiNI4VBKDnxHkTl97xqZHjuvqztvM/edit?usp=sharing

**Comment by rohbotics** [comment]
Closing this because it is now its own repo with it's own issues.
