### ISSUE TITLE
Alexy Floor follow

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/ubiquity_main#216]
This is the issue for making progress on alexy floor follow.

This will be done when the software meets the requirements of the software components of breadcrumb described here:

https://docs.google.com/document/d/1t24kzd8stWFtDZgiNI4VBKDnxHkTl97xqZHjuvqztvM/edit?usp=sharing

Alexy floor follow:
https://github.com/rohbotics/ground-fiducials

Latest code:
https://github.com/MoffKalast/ground_fiducials

**Comment by MoffKalast** [comment]
Per new planning, the development of floor follow will continue on a different codebase.

**Comment by MoffKalast** [comment]
The codebase is now being continued here: https://github.com/MoffKalast/ground_fiducials
