### ISSUE TITLE
ROS build Cleanup

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/ubiquity_main#224]

**Comment by rohbotics** [comment]
@davecrawley Can you explain what this issue is?

**Comment by MoffKalast** [comment]
I suspect it may be a blanket issue that covers [https://github.com/UbiquityRobotics/ubiquity_buildbot/issues](https://github.com/UbiquityRobotics/ubiquity_buildbot/issues).

**Comment by davecrawley** [comment]
Its me not being very structured! I think you've logged separate issues for all the ROS build system cleanup - this issue should be closed.

**Comment by rohbotics** [comment]
Closing because it is already covered by other issues.
