### ISSUE TITLE
We should set ROS_HOSTNAME the smart way

### ISSUE THREAD

**Issue by mjstn** [UbiquityRobotics/ubiquity_main#231]
We call /etc/ubiquity/env.sh but we use  ROS_HOSTNAME there.

In our new images we should use the 'smart way' of setting ROS_HOSTNAME.
I suggest in .bashrc prior to calling env.sh  OR in env.sh, your choice but it must be exported properly.

# ROS environment
export ROS_HOSTNAME=`cat /etc/hostname`.local
export ROS_MASTER_URI=http://`cat /etc/hostname`.local:11311

If we don't do this a user changing host name on his own gets ros core not starting right.

**Comment by rohbotics** [comment]
If you look at `/etc/ubiquity/env.sh` this is all it does.

 It's in a separate file instead of in the bashrc for the user that way it can be easily sourced by all users (in case a customer wants multiple users), and also by the startup script, without having to change things in multiple places.
