### ISSUE TITLE
Packages missing files

### ISSUE THREAD

**Issue by kristjanp28** [UbiquityRobotics/ubiquity_main#232]
I was trying to get docking_node to work but I had some issues with following packages:
- fiducial_slam
- move_base_msgs
- move_basic

So what I did to fix the issue:

1. Made a backup of demos and deleted demos file

1. put all above mentioned files into catkin_ws/src and compiled with catkin_make

1. deleted mentioned files from catkin_ws/src and put in the demos folder back
1. Again compiled everything with catkin_make.

And docking_node started working without any problem.

**Comment by rohbotics** [comment]
I think this was a configuration issue and we haven't seen it come up again, closing.
