### ISSUE TITLE
Raspberry Pi 4 B refuses SSH connection

### ISSUE THREAD

**Issue by kristjanp28** [UbiquityRobotics/ubiquity_main#235]
Refuses SSH connection in AP mode or connected to the network. Tried creating SSH file in BOOT partition.

**Comment by karpandrew12** [comment]
Im having the exact issue. Im trying to ssh into my raspberry pi 4 from my ubuntu machine and its stating the password is incorrect.

**Comment by karpandrew12** [comment]
I ended up figuring out how to fix this. Before i tried ssh from development computer to robot comp with ssh pi@ipaddress. This was incorrect. The correct way is to ssh the name of your system in replacement to "pi". For example : ssh ubuntu@ipaddress.

I hope this helps.

**Comment by kristjanp28** [comment]
> I ended up figuring out how to fix this. Before i tried ssh from development computer to robot comp with ssh pi@ipaddress. This was incorrect. The correct way is to ssh the name of your system in replacement to "pi". For example : ssh ubuntu@ipaddress.
> 
> I hope this helps.

There is no issue with wrong password. There is an issue with Pi itself or with the network that we are using.

**Comment by rohbotics** [comment]
Closing this because we found out that the issue was the ssh systemd service being configured badly.

**Comment by an-dr** [comment]
@rohbotics should we update the image? Or could you give some hint hot to fix it on our existing image? I have the same issue, but my fix is to wait about 5-10 minutes :)

**Comment by rohbotics** [comment]
@an-dr The fix is here: https://forum.ubiquityrobotics.com/t/ros-image-on-raspberry-pi-4/326/59?u=rohbotics

It will be in the next image once we release that.
