### ISSUE TITLE
Need to recognize MCB U3 as PCF8574 or PCF8574A in launch_core.py

### ISSUE THREAD

**Issue by mjstn** [UbiquityRobotics/ubiquity_main#236]
We need to allow production screw-ups that incorrectly procure PCF8574A parts at I2C addr of 0x38 instead of the specified PCF8574 part that is at addr 0x20.
This will just make our code more robust to an easy to make procurement problem.

Also in doing this we should have the board revision reported from launch_core.py match the resistors loaded and not be off by 1 as it is now.  Rev 5.1 boards should report 51 and rev 5.2 should report 52. The offset of 1 is just going to lead to a lot of confusion as we move forward.

**Comment by rohbotics** [comment]
Closing this because we decided to go with the hardware solution
