### ISSUE TITLE
Image 2020-02-10-ubiquity-xenial-lxde Compressed Data Is Corrupt

### ISSUE THREAD

**Issue by astroesteban** [UbiquityRobotics/ubiquity_main#240]
Hello,

I downloaded the latest image from your website on Mac OS 10.15.4 and when I execute the following command:

`xz -d image_name.img.xz`

I receive the following error:

`Compressed data is corrupt`

It all works fine with image https://ubiquity-pi-image.sfo2.cdn.digitaloceanspaces.com/2019-06-19-ubiquity-xenial-lxde-raspberry-pi.img.xz

**Comment by rohbotics** [comment]
Can you verify that the sha256sum is correct?

`sha256sum image_name.img.xz` should have the same result as posted on the website.

**Comment by astroesteban** [comment]
On Mac OS there is no sha256sum so I used `shasum -a 256 image_name.img.xz` and ended up getting **31c9813644010b4bafc82105627a8941db957b53be6c2b6b506e4283cbc0f6e6** which differs form the one on the website.

**Comment by rohbotics** [comment]
I get the same checksum when I download it, sounds like something got corrupted on the way to you.

**Comment by astroesteban** [comment]
Might be an Apple thing. I tried downloading it through my iPhone and I get the same checksum that my Mac is getting. I'll try on an Ubuntu VM.

**Comment by rohbotics** [comment]
Closing due to age and no recent complaints.
