### ISSUE TITLE
Wiki.js/learn.ubiquityrobotics tutorial for LS lidar

### ISSUE THREAD

**Issue by MoffKalast** [UbiquityRobotics/ubiquity_main#261]

**Comment by JanezCim** [comment]
Started with lidar tutorials here: 
https://github.com/UbiquityRobotics/learn/blob/feature-lslidar-connection/doing_more/ls_lidar_setup_noetic.md
https://github.com/UbiquityRobotics/learn/blob/feature-lslidar-connection/doing_more/ls_lidar_setup_common.md
Feel free to add stuff

**Comment by JanezCim** [comment]
The tutorials are ready on a PR on learn repo, once that is merged, this can be merged as well
