### ISSUE TITLE
Temporary LS lidar mount, getting it into production

### ISSUE THREAD

**Issue by MoffKalast** [UbiquityRobotics/ubiquity_main#262]

**Comment by JanezCim** [comment]
@AljazKrsnik currently the design of the small lidar holder is like this:
![image](https://user-images.githubusercontent.com/8426792/151754640-dbf8c92b-e09f-4a5d-8057-b11c6f456f97.png)

We need to rearrange the small holes to fit the new mounting holes of the LD lidar (green circles) @MoffKalast can you provide measures for those holes and a couple of pics of the lidar with the bottom plate? @MoffKalast if you can, please double check those measures also with the real lidar so we are sure they are correct. @AljazKrsnik I think those will become holes with M3 thread inserts, which is going to be easier to produce and easier to find the screws for. 

When we have the new model please upload new version to zoho and send the link here. Stephen that wants to produce these wants this fairly soon, so if we could do it in the beginning of this week, it would be great, thanks!

**Comment by AljazKrsnik** [comment]
Hello. Will do this by tomorrow.

V V pon., 31. jan. 2022 ob 08:35 je oseba Janez Cimerman <
***@***.***> napisala:

**Comment by MoffKalast** [comment]
Aight so, here are some pictures of the bottom plate for reference, and a reasonably accurate STL of it: https://workdrive.zohoexternal.com/folder/pykvle29eeb8d8c784bc584da07d6e40484bb

![20220131_152640](https://user-images.githubusercontent.com/9977799/151815530-115b7753-f383-4fc4-a3a5-de8bba25e7bb.jpg)

![20220131_152700](https://user-images.githubusercontent.com/9977799/151815536-986b454e-37cc-4dc8-a2d0-fa401ad4bc07.jpg)

![20220131_152710](https://user-images.githubusercontent.com/9977799/151815524-015cef54-4ad5-4a99-b2d4-7c4c1ac0ab85.jpg)

Note that arrow on the side in the last pic, that's the URDF forward direction for the lidar. I hope that helps.

**Comment by AljazKrsnik** [comment]
Can you send me step file? With this file the scale is a bit f***** up. Just want to really get the correct measurement.
![LIDAR direction](https://user-images.githubusercontent.com/87651656/151838283-ebdd100e-5031-4729-a088-ae4ab31437e4.GIF)

**Comment by AljazKrsnik** [comment]
Is the orientation correct? I will send you more pics when this is confirmed.

**Comment by MoffKalast** [comment]
There actually is no step file, I threw this together in tinkercad last week when I needed a printed mount for my test robot.

But that scale does look roughly right that you have there. This lidar is rather tiny. I'm not sure if this position has the lidar pointing backwards of forwards, but that's pointing it backwards in terms of yaw.

Holes should be M3, and here are the two main dimensions:

![image](https://user-images.githubusercontent.com/9977799/151844558-76d3507b-b7b6-4cb5-a910-2b110209b139.png)

**Comment by AljazKrsnik** [comment]
Ok. This is good enough. I just needed a scale. Thx

**Comment by JanezCim** [comment]
A bit unrelated but still: @AljazKrsnik after this is done, would it be also possible to fit this into breadcrumb lidar holder?

**Comment by AljazKrsnik** [comment]
No problem. Will try to make adjustments today

V tor., 1. feb. 2022 15:36 je oseba Janez Cimerman ***@***.***>
napisala:

**Comment by AljazKrsnik** [comment]
Please confirm the orientation of the lidar in both cases.
![ORIENT+CHARGING HOLE](https://user-images.githubusercontent.com/87651656/152018457-7793ec1b
![LIDAR HOLDER MOUNT2](https://user-images.githubusercontent.com/87651656/152018477-d6939a96-d73b-4dd1-a3f5-5ca21078e7f7.GIF)

![LIDAR HOLDER MOUNT](https://user-images.githubusercontent.com/87651656/152018474-774f53b6-caa5-4956-8f56-f3109c19e63a.GIF)

![ORIENT+CHARGING HOLE2](https://user-images.githubusercontent.com/87651656/152018470-710fab0a-8453-4cd0-a90b-17652a07c2fd.GIF)
-50ac-4614-b8e5-a9d670f2f336.GIF)

**Comment by AljazKrsnik** [comment]
![ORIENT+CHARGING HOLE](https://user-images.githubusercontent.com/87651656/152018683-287e8de3-5363-4931-bd90-51a6f8258ce8.GIF)

**Comment by AljazKrsnik** [comment]
Regarding new/old matter- charging hole. Are there any changes( dimension vise)?

**Comment by AljazKrsnik** [comment]
![right orientation](https://user-images.githubusercontent.com/87651656/152027426-dce1c9c0-0c27-4e9e-9c55-b8bf24e89672.GIF)

This is the right orientation. Am i right?

**Comment by anfederman** [comment]
Is this for LS, LD06 or both?

**Comment by AljazKrsnik** [comment]
Both

**Comment by JanezCim** [comment]
@AljazKrsnik I think that yes, the forward arrow on lidar should be pointing into forward direction of the robot, so i think that this image is correct. but please @MoffKalast confirm this. 
![image](https://user-images.githubusercontent.com/8426792/152119957-dfeb5cf1-cdc7-4780-9b1d-7e69d3f8276d.png)

This is not good, the lidar holder for small LD lidar will be mounted upside down. This way the small ld lidar will also be able to see between the bottom shelf and shell.
![image](https://user-images.githubusercontent.com/8426792/152120337-72a9096c-2b87-4c33-a487-630d8b3b074f.png)

**Comment by MoffKalast** [comment]
Yeah that looks good for the top pic, the red indicator should be facing the opposite way the LS lidar cable does.

**Comment by AljazKrsnik** [comment]
The pictures show how much LIDAR mean is intersected in both aplications.
I think with the LIDAR N30105B v7 there is no problem.
With LIDAR 19, there is a lot of intersection.
My solution: I would lower the holes for LIDAR mount( shelf) on main cover for 9 mm. In that case there would be no beam intersection
![LIDAR BEAM PATH](https://user-images.githubusercontent.com/87651656/152559274-de7eabfd-3c12-46f0-a5bb-a0d7e982abb5.GIF)
.
Please correct me if i am wrong or my 3D model is different from phisical MAGNI 5

![LIDAR DTOF LD 19 BEAM](https://user-images.githubusercontent.com/87651656/152559285-bfdb6550-8593-40f8-bfbc-505301169afa.GIF)
.

**Comment by JanezCim** [comment]
@AljazKrsnik can you send me a zoho link for the small temporary lidar holder so i can send it forward for test production?

**Comment by AljazKrsnik** [comment]
https://workdrive.zoho.com/home/g9vop387248f4f5304dde876eb982824d88c5/ws/g9vop0ead768c4254422e9332d4e4fd4a414b/folders/mskzr6baafd621a464ababc8453d77d2219ca

**Comment by JanezCim** [comment]
> https://workdrive.zoho.com/home/g9vop387248f4f5304dde876eb982824d88c5/ws/g9vop0ead768c4254422e9332d4e4fd4a414b/folders/mskzr6baafd621a464ababc8453d77d2219ca

This is not the correct termporary lidar holder, its breadcrumb lidar holder. What i need is the straight holder that goes into the lidar box

**Comment by AljazKrsnik** [comment]
Right now, i have added thecorrect mount on the same link.

V V sre., 9. feb. 2022 ob 12:34 je oseba Janez Cimerman <
***@***.***> napisala:

**Comment by JanezCim** [comment]
the "small temporary lidar holder_TEST_HEX_NUT" you can probably remove from there since that holder is ment for breadcrumb and not for magni

**Comment by JanezCim** [comment]
Status update: stephen from leishen has recieved the 3d file and we are in discussions about producing it

**Comment by AljazKrsnik** [comment]
I have shaped a a mount JUST for LIDAR LD19. Its smaller and less rivets with a lot of clearance. Tell me what you think
![LIDAR 19 MOUNT](https://user-images.githubusercontent.com/87651656/153578569-e434c9f8-52f6-4134-9015-3e45ca47a033.GIF)
![LIDAR 19 MOUNT_1](https://user-images.githubusercontent.com/87651656/153578579-5e33cc94-a509-4582-bd4a-f34d4e5db718.GIF)
![LIDAR 19 MOUNT_2](https://user-images.githubusercontent.com/87651656/153578587-dba6b3c2-cea4-4e6f-b026-f02a23ab5c1a.GIF)
.

**Comment by JanezCim** [comment]
@AljazKrsnik this i think its safe to say its unrelated to the original issue of the temporary lidar mount, I opened up an issue here https://github.com/UbiquityRobotics/breadcrumb/issues/353 which is going to be specifically for the breadcrumb ls lidar mount
