### ISSUE TITLE
EZ-Map Improvement Roadmap

### ISSUE THREAD

**Issue by MoffKalast** [UbiquityRobotics/ubiquity_main#263]
![theplan drawio (4)](https://user-images.githubusercontent.com/9977799/152425830-614996a8-d589-43b9-b397-dad64322ada7.png)

The plan for sorting out navigation that is.

**Comment by JanezCim** [comment]
@MoffKalast irl after finishing The Plan:
![image](https://user-images.githubusercontent.com/8426792/151809254-98e3876a-32f7-4005-8789-e8e4ae11727c.png)

**Comment by MoffKalast** [comment]
![giphy](https://user-images.githubusercontent.com/9977799/151814799-559a5728-47c6-4bd1-9580-679360fa4377.gif)
