### ISSUE TITLE
LS Lidar Metal Ethernet Plug

### ISSUE THREAD

**Issue by MoffKalast** [UbiquityRobotics/ubiquity_main#269]
Can dangerously spark.

**Comment by mjstn** [comment]
The ethernet cable connector for the Lidar has a large metal covering that is ground.    We plug this cable into our cpu in a very tight area where it is very easy to take out the cable or be putting it into the cpu and it can slip from a persons fingers and fall onto our main controller board where there are many different live voltages.     

If this cable were a typical plastic ended ethernet cable the risk of shorting out and causing damage would be greatly reduced.

Here is the cable connector 
![LidarEnetCableWithExposedGround](https://user-images.githubusercontent.com/7555603/157414434-94401d99-8a37-438a-80a9-e14dfeda2d86.jpg)

**Comment by NejaE** [comment]
Reported to Leishen, ordered a sample cable, should get an outdate by Apr 26th.
