### ISSUE TITLE
Partybot update

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/ubiquity_main#27]

**Comment by jim-v** [comment]
We need a C++ node that subscribes to an image topic, runs face detection, and publishes  sensor_msgs/RegionOfInterest messages.

**Comment by davecrawley** [comment]
Do we need just face detection? Or do we need face detection, lock on with LK_feature extraction etc?

David

**Comment by rohbotics** [comment]
We probably want to do some kind of optical flow based tracking to improve performance

**Comment by jim-v** [comment]
Yes, I was just documenting what's needed to resurrect the old partybot behavior as a first step.

**Comment by rohbotics** [comment]
Superseded by #90 #91 and #92
