### ISSUE TITLE
Move-basic on loki seems to spin randomly

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/ubiquity_main#43]

**Comment by jim-v** [comment]
The odometry looks good, but the rotation does not slow down as the target orientation is reached. This appears to be related to UbiquityRobotics/loki_base_node#2 in that there appears to be an issue with motor speed requests being handled by the firmware.

**Comment by rohbotics** [comment]
Could it also be https://github.com/UbiquityRobotics/loki_base_node/issues/1? What is the cpu usage of loki_base_node when move_basic-ing?

With teleop it can fall behind and lag on executing commands, maybe that is causing the issue.

**Comment by jim-v** [comment]
That's part of the problem, and it does continue to rotate for a few seconds after the last command was sent.   However, changing the rate of the rotate loop from 50 to 5 did not cause it to behave correctly.
It can be made to behave better by setting the `min_angular_velocity` parameter to 0.5

**Comment by jim-v** [comment]
The CPU usage of the loki_base_node process is around 12% when idle and 40% when going to a goal.

**Comment by waynegramlich** [comment]
Assigning this task to me is probably not optimal. I no longer have a Loki.  It sounds like there is a fundamental bug in the software stack.  It could be loki_base_node or it could be the firmware.  The first step is to verify that the PID loops are working correctly.  This is done using `minicom` (or equivalent) to send `m left right` commands to the Loki.  The `e` command returns encoder values.  This response is pathetic, but that is the best I can suggest right now.
