### ISSUE TITLE
RTC battery should come with robot

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/ubiquity_main#59]

**Comment by rohbotics** [comment]
Did this happen?

**Comment by davecrawley** [comment]
No, but it will most likely get fixed in the next round if the issues surrounding batteries in airfreight products can be overcome. I have to assume that the battery is small enough that a work around is possible. But I do know it does require additional documentation.

David

**Comment by rohbotics** [comment]
Status on this?

**Comment by mjstn** [comment]
We are actively working to structure the battery to the product so this happens but it is not fully implemented just yet.
