### ISSUE TITLE
Robot Commander on latest image

### ISSUE THREAD

**Issue by anfederman** [UbiquityRobotics/ubiquity_main#63]
testing new image

**Comment by anfederman** [comment]
I tested on the latest image.  rosbridge_websocket was not being launched by default. After launching, I was still unable to connect via the App.  I was able to drive the robot with keyboard teleop from a laptop.  I suspect the rosbridge_websocket parameters are not set correctly on the new image.

**Comment by jrlandau** [comment]
After launching rosbridge_websocket, I was able to drive the robot using
the app.  So you and I need to get together on using the app.  But the fact
that rosbridge is not being launched by default is something to be fixed in
the image.  Or so it seems to me.

**Comment by rohbotics** [comment]
Replaced by #64
