### ISSUE TITLE
navigation not running after robot boots

### ISSUE THREAD

**Issue by jrlandau** [UbiquityRobotics/ubiquity_main#67]

**Comment by rohbotics** [comment]
Please provide a detailed "Definition of Done" for this issue.

Do we want fiducial localization or just in the local frame as we discussed during the huddle?

**Comment by jrlandau** [comment]
I'm hoping DC will provide an answer.

**Comment by jrlandau** [comment]
Definition of done: after the robot boots, Robot Commander can successfully issue commands for measured movements and for waypoints.
