### ISSUE TITLE
Downloading images to Windows and Mac

### ISSUE THREAD

**Issue by jrlandau** [UbiquityRobotics/ubiquity_main#69]
If users are to download images (I'm not sure about this), the download page should have instructions for Win and Mac as well as Linux.

**Comment by jrlandau** [comment]
Criterion for done: 
paragraph on installing images should cover windows and mac.  The downloads page should be reachable from the web site.
The downloads page is https://downloads.ubiquityrobotics.com/

**Comment by rohbotics** [comment]
I think this is resolved with the etcher recommendation.
