### ISSUE TITLE
Fix PID tuning

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/ubiquity_main#72]
The PID tuning currently is such that in normal operation there is a variation between target and actual position that corresponds to about 7 ticks. Further, there is no I term so I accumulator always reaches the integral limit without having any effect on the robot. We need to a) Tune the PID loop so that in normal operation there is rarely more than 1 tick difference between target and actual 2) Tune the integral, acceleration and other limits so that in normal operation they are never reached. We need to do this while ensuring there is no oscillation in the system. Currently we have a Proportional controller, my hypothesis is that the large momentum of the wheel probably already provides a fairly strong I term intrinsically, perhaps we need to tune it as a PD controller, then add in an I term later.

**Comment by rohbotics** [comment]
@davecrawley please be specific about the issue in the description. Otherwise we end up with broad issues that are never closeable.

**Comment by rohbotics** [comment]
There is possible bug here: the robot keeps rolling well after we tell it to stop. This could just be bad PID params
