### ISSUE TITLE
System that reports version installed

### ISSUE THREAD

**Issue by davecrawley** [UbiquityRobotics/ubiquity_main#73]

**Comment by rohbotics** [comment]
Please put an issue description about what was discussed.

**Comment by jim-v** [comment]
We discussed having a command that a user could run that would gather version data about our software, to help with support requests.

Definition of done: command exists and is in image

**Comment by jim-v** [comment]
Something like this

[version.py.txt](https://github.com/UbiquityRobotics/ubiquity_main/files/1424462/version.py.txt)

**Comment by jrlandau** [comment]
As congressman from East Overshoe, I note that my constituents want this
info to be available in RC.

**Comment by dorkamotorka** [comment]
https://github.com/UbiquityRobotics/magni_robot/pull/128 Implements this.
