### ISSUE TITLE
SD Card image needs update

### ISSUE THREAD

**Issue by anfederman** [UbiquityRobotics/ubiquity_main#77]
Last image 8/06  need update with Latest PiFi, teleoptwist-keyboard, Loki catkin_ws/src/ubiquity_launches and sudo apt update to reflect changes in code.

**Comment by jim-v** [comment]
PiFi is updated via apt-get upgrade.  A Kinetic package sync has occurred, and there are currently no packages that need to be built from source.
Need to know what repos are required for Loki.

**Comment by rohbotics** [comment]
The 2017-11-12 image has the latest pifi, and teleop-twist-keyboard, no ubiquity_launches.
