### ISSUE TITLE
Create {loki,magni} rviz packages

### ISSUE THREAD

**Issue by jim-v** [UbiquityRobotics/ubiquity_main#95]

**Comment by rohbotics** [comment]
should be `loki_viz` and `magni_viz` in case we want to other non-rviz stuff?

**Comment by anfederman** [comment]
Any progress on this?

**Comment by jim-v** [comment]
We discussed this earlier and agreed to do https://github.com/UbiquityRobotics/loki_base_node/issues/6 first.

**Comment by jim-v** [comment]
What do we want to put in there?

- [ ] raspicam image
- [ ] sonars (without tf)
- [ ] fiducial markers
- [ ] move_basic plan
- [ ] move_basic obstacles
- [ ] robot model
