### ISSUE TITLE
Extra "/" in README.md

### ISSUE THREAD

**Issue by cpeavy2** [UbiquityRobotics/ubiquity_main#98]
Extra "/" in intro_to_ros README.md ... under "Optional, but highly recommended:"
 
git clone /https://github.com/pirobot/rbx1
 
Thanks,
Camp

**Comment by rohbotics** [comment]
Thanks for finding this and opening an issue.

The intro_to_ros stuff is not a Ubiquity Robotics project, I suggest you open the issue on https://github.com/SV-ROS/intro_to_ros, where the people who can fix it will see it.
